#!/bin/bash

##############################
#                            #
#   Wireguard Configurator   #
#                            #
##############################

# config file

# config version, gets checked by scripts. DO NOT CHANGE!
configver=3

# main directory, defaults to /etc/wireguard/
maindir=${maindir:-/etc/wireguard/}

# wgc directory, defaults to ./wgc/
wgcdir=${wgcdir:-${maindir}wgc/}

# sleeptimer, how long to pause for softerror, defaults to 3
sleeptimer=${sleeptimer:-3}

# cert subdirectory, defaults to ./certificates/
certdir=${certdir:-${maindir}certs/}

# config subdirectory, defaults to ./client-configs/
confdir=${confdir:-${maindir}client-configs/}

# interface to configure, defaults to wg0
wginterface=${wginterface:-wg0}

# network (/24) to use for vpn clients, only use first 3 octets, defaults to 10.255.255.
wgnetwork=${wgnetwork:-10.255.255.}

# server ip address within the given network, defaults to 1
wgserverip=${wgserverip:-1}

# server port for wireguard to listen on, defaults to 51820
wgserverport=${wgserverport:-51820}

# default name for clients, will increment the number, defaults to client-#
wgclientdefaultname=${wgclientdefaultname:-client\-}

# client config: dns server that was pushed, defaults to 1.1.1.1
wgclientdns=${wgclientdns:-1.1.1.1}

# client config: hostname to connect to, defaults to system hostname
wgclienthostname=${wgclienthostname:-$(hostname)}

# client config: port that the client connects to, defaults to wgserverport
wgclientport=${wgclientport:-${wgserverport}}

# generator: user that owns the copy of the client configs
wgcopyuser=${wgcopyuser:-${SUDO_USER}}

# generator: folder to copy client configs to
wgcopydest=${wgcopydest:-/home/${wgcopyuser}/wireguard-configs/}

# github download url
giturl=https://raw.githubusercontent.com/NiiWiiCamo/wireguard-configurator/master/
